project:
  type: website
  output-dir: docs

website:
  title: "matteo-24"
  favicon: images/favicon.png
  navbar:
    title: false
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: documents/cv-fr-matteo.pdf
        text: CV
        target: _blank
format:
  html:
    theme: [united, styles.scss]
    mainfont: "Roboto"